### ISSUE TITLE
Error raised, which is confusing for me. Please see the following

### ISSUE THREAD

**Issue by jiangxu87** [bradleyfay/NBAStats#6]
I followed all the steps, but the following error raised, which is confusing for me. I would appreciate it very much if you could help.

>>> import nbastats.nbastats as nbastats
>>> george = nbastats.ShotChart('202331')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbastats/nbastats.py", line 38, in __init__
    self._x = self._x.json()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by kpelechrinis** [comment]
I have exactly the same issue.  Any luck fixing it?

**Comment by bradleyfay** [comment]
It's a Python 3 compatibility issue that arose from a refactor. 

Have you tried updating to the latest version? Not sure if that fixes it, but it's worth a try.

**Comment by kpelechrinis** [comment]
I do not think it has to do with the version - I actually tried DataJoy which has all the latest versions for packages, Python etc. and I got the same error.  I tried to download the data "manually" through wget and then load the json file using json.load() and I got an error while loading again.  It might be something with the json file return from the NBA API.

**Comment by bradleyfay** [comment]
Ah. Didn't realize what package this was. 

I stopped developing this and started a new package, py-Goldbserry that you should check out. 

GitHub.com/bradleyfay/py-goldsberry

**Comment by kpelechrinis** [comment]
oh ok! Cool; thanks - I will check it out!
